**ASSIGNMENT-1**


Create 1D, 2D, and 3D tensors using PyTorch and NumPy.
Show Basic Operations: Element-wise addition, subtraction, multiplication, and division.
Dot product and matrix multiplication.
Indexing and Slicing examples (Boolean masking, extracting subtensors)
Use .view(), .reshape(), .unsqueeze(), and .squeeze() in PyTorch. Compare with .reshape in Numpy
Broadcasting- Perform operations with tensors of different shapes.
In-place vs Out-of-place operations

Create 1D, 2D, and 3D tensors using PyTorch and NumPy.



In [ ]:
import numpy as np

In [ ]:
#1D NumPy Array (Vector)
arr_1d_np = np.array([1, 2, 3, 4])
print("1D NumPy Array:")
print(arr_1d_np)


1D NumPy Array:
[1 2 3 4]


In [ ]:
#2D NumPy Array (Matrix)
arr_2d_np = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
print("\n2D NumPy Array:")
print(arr_2d_np)


2D NumPy Array:
[[1 2 3]
 [4 5 6]]


In [ ]:
#3D NumPy Array
arr_3d_np = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])
print("\n3D NumPy Array:")
print(arr_3d_np)



3D NumPy Array:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
import torch


In [ ]:
#1D PyTorch Tensor
tensor_1d = torch.tensor([1, 2, 3, 4])
print("\n1D PyTorch Tensor:")
print(tensor_1d)



1D PyTorch Tensor:
tensor([1, 2, 3, 4])


In [ ]:
#2D PyTorch Tensor
tensor_2d = torch.tensor([
    [1, 2, 3],
    [4, 5, 6]
])
print("\n2D PyTorch Tensor:")
print(tensor_2d)



2D PyTorch Tensor:
tensor([[1, 2, 3],
        [4, 5, 6]])


In [ ]:
#3D PyTorch Tensor
tensor_3d = torch.tensor([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])
print("\n3D PyTorch Tensor:")
print(tensor_3d)



3D PyTorch Tensor:
tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])


Show Basic Operations: Element-wise addition, subtraction, multiplication, and division.
Dot product and matrix multiplication.

1D NumPy Array – Element-wise Operations

In [ ]:
import numpy as np

a = np.array([10, 20, 30])
b = np.array([2, 4, 5])


#Addition
print(f"1D NumPy Array – Addition: {a+b}")

#Subtraction
print(f"1D NumPy Array – Subtraction: {a-b}")

#Multiplication
print(f"1D NumPy Array –Multiplication: {a*b}")

#Division
print(f"1D NumPy Array – Division: {a/b}");

1D NumPy Array – Addition: [12 24 35]
1D NumPy Array – Subtraction: [ 8 16 25]
1D NumPy Array –Multiplication: [ 20  80 150]
1D NumPy Array – Division: [5. 5. 6.]


2D NumPy Array – Element-wise Operations

In [ ]:
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

#Addition
print(f"2D NumPy Array – Addition: {A+B}")

#Subtraction
print(f"2D NumPy Array – Subtraction: {A-B}")

#Multiplication
print(f"2D NumPy Array –Multiplication: {A*B}")

#Division
print(f"2D NumPy Array – Division: {A/B}");


2D NumPy Array – Addition: [[ 6  8]
 [10 12]]
2D NumPy Array – Subtraction: [[-4 -4]
 [-4 -4]]
2D NumPy Array –Multiplication: [[ 5 12]
 [21 32]]
2D NumPy Array – Division: [[0.2        0.33333333]
 [0.42857143 0.5       ]]


1D Pytorch Tensor – Element-wise Operations

In [ ]:
from re import X
import numpy as np

x = torch.tensor([10, 20, 30])
y = torch.tensor([2, 4, 5])


#Addition
print(f"1D pytorch tensor – Addition: {x+y}")

#Subtraction
print(f"1D pytorch tensor – Subtraction: {x-y}")

#Multiplication
print(f"1D pytorch tensor –Multiplication: {x*y}")

#Division
print(f"1D pytorch tensor – Division: {x/y}");

1D pytorch tensor – Addition: tensor([12, 24, 35])
1D pytorch tensor – Subtraction: tensor([ 8, 16, 25])
1D pytorch tensor –Multiplication: tensor([ 20,  80, 150])
1D pytorch tensor – Division: tensor([5., 5., 6.])


2D pytorch tensor – Element-wise Operations

In [ ]:
P = torch.tensor([[1, 2],
              [3, 4]])

Q =torch.tensor([[5, 6],
              [7, 8]])

#Addition
print(f"2D pytorch tensor – Addition: { P+Q}")

#Subtraction
print(f"2D pytorch tensor – Subtraction: {P-Q}")

#Multiplication
print(f"2D pytorch tensor –Multiplication: {P*Q}")

#Division
print(f"2D pytorch tensor – Division: {P/Q}");


2D pytorch tensor – Addition: tensor([[ 6,  8],
        [10, 12]])
2D pytorch tensor – Subtraction: tensor([[-4, -4],
        [-4, -4]])
2D pytorch tensor –Multiplication: tensor([[ 5, 12],
        [21, 32]])
2D pytorch tensor – Division: tensor([[0.2000, 0.3333],
        [0.4286, 0.5000]])


Dot product in Numpy & Pytorch

In [ ]:
#Numpy array dot product using np.dot()
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

result = np.dot(a, b)
print(result)


#pytorch tensor dot product using torch.dot()
x = torch.tensor([10, 20, 30])
y = torch.tensor([2, 4, 5])
result = torch.dot(x, y)
print(result)



32
tensor(250)


Matrix Multiplication for 2D Numpy aaray and pytorch tensor

In [ ]:
A = np.array([[1, 2],
                  [3, 4]])

B = np.array([[5, 6],
                  [7, 8]])

print(f"2D Numpy array-matrix multiplication: {A@B}");


A = torch.tensor([[1, 2],
                  [3, 4]])

B = torch.tensor([[5, 6],
                  [7, 8]])

print(f"2D pytorch tensor -matrix multiplication: {A@B}");



2D Numpy array-matrix multiplication: [[19 22]
 [43 50]]
2D pytorch tensor -matrix multiplication: tensor([[19, 22],
        [43, 50]])


Indexing and Slicing examples (Boolean masking, extracting subtensors)

In [ ]:
import torch
import numpy as np

t = torch.tensor([[10, 20, 30],
                  [40, 50, 60]])
#indexing
print(t[0, 1])

#slicing
print(t[:,1])
print(t[0,:])

#extracting subtensor in tensor
print(t[0:2,1:2])




tensor(20)
tensor([20, 50])
tensor([10, 20, 30])
tensor([[20],
        [50]])


In [ ]:
#boolean masking: Selecting elements from an array using a condition that returns True or False.
#boolean masking on tensor
mask = t > 30
print(mask)
print(t[mask])

#boolean masking on array
arr=np.array([[10,40,30],[20,65,26],[56,12,34]]);
mask=arr>30
print(mask)
print(arr[mask])

#extracting submatrix in array
print(arr[0:2,1:2])




tensor([[False, False, False],
        [ True,  True,  True]])
tensor([40, 50, 60])
[[False  True False]
 [False  True False]
 [ True False  True]]
[40 65 56 34]
[[40]
 [65]]


In [ ]:
# .view()
import torch
x=torch.tensor([1,2,3,4,5,6])
y=x.view(2,3)
print(y)
print(x)

# .reshape()
z=x.reshape(2,3)
print(z)
print(x)

#.unsqueeze()
y = x.unsqueeze(0)
print(y)
print(y.shape)

z=x.unsqueeze(1)
print(z)
print(z.shape)


#.squeeze()
print(y.squeeze(0))
print(z.squeeze(1))





tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([1, 2, 3, 4, 5, 6])
tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([1, 2, 3, 4, 5, 6])
tensor([[1, 2, 3, 4, 5, 6]])
torch.Size([1, 6])
tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6]])
torch.Size([6, 1])
tensor([1, 2, 3, 4, 5, 6])
tensor([1, 2, 3, 4, 5, 6])


Broadcasting- Perform operations with tensors of different shapes.

In [ ]:
import torch

a = torch.tensor([[1, 2, 3],
                  [4, 5, 6]])

b = torch.tensor([10, 20, 30])

print(a + b)


tensor([[11, 22, 33],
        [14, 25, 36]])


In [ ]:
#out-of-place operation
x = torch.tensor([1, 2, 3])
y = x + 5

print(x)
print(y)


#in-place operation
x = torch.tensor([1, 2, 3])
x.add_(5)

print(x)



tensor([1, 2, 3])
tensor([6, 7, 8])
tensor([6, 7, 8])
